// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaverSearch.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SaverSearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaverSearchDbContext))]
    [Migration("20260701082216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SaverSearch.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23a2a3ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "TVs, laptops, phones, and smart home appliances",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("8b72de70-c081-420a-9d62-f6cb3ce183a3"),
                            Description = "Groceries, weekly shops, and household essentials",
                            IsActive = true,
                            Name = "Supermarkets"
                        },
                        new
                        {
                            Id = new Guid("501bd346-63e8-466d-b873-67ca2b6eb2b5"),
                            Description = "Clothing, footwear, and accessories",
                            IsActive = true,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = new Guid("3d64c148-d3c5-4148-912f-db4fe72b0c95"),
                            Description = "Furniture, garden, and home improvement decor",
                            IsActive = true,
                            Name = "Home"
                        },
                        new
                        {
                            Id = new Guid("9a8cd34a-9ef8-4ca7-9e7f-b67f2e1a3bc8"),
                            Description = "Hotels, flights, holidays, and transport",
                            IsActive = true,
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsExclusive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("MaximumReward")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumSpend")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terms")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferTypeId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RetailerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.OfferType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OfferTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Return of a percentage of the amount spent to the consumer",
                            Name = "Cashback"
                        },
                        new
                        {
                            Id = new Guid("22c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Direct price reduction applied to purchase price",
                            Name = "Discount"
                        },
                        new
                        {
                            Id = new Guid("33c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Loyalty system points earned per dollar/pound spent",
                            Name = "Reward Points"
                        },
                        new
                        {
                            Id = new Guid("44c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "A discount code or certificate for specific promotions",
                            Name = "Voucher"
                        },
                        new
                        {
                            Id = new Guid("55c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Cashback specifically directed to pay down linked mortgage balances",
                            Name = "Mortgage Cashback"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(2525),
                            Description = "UK's highest paying cashback site",
                            IsActive = true,
                            Name = "TopCashback",
                            UpdatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(2528),
                            Website = "https://www.topcashback.co.uk"
                        },
                        new
                        {
                            Id = new Guid("22b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3164),
                            Description = "Great rates and easy cashback search",
                            IsActive = true,
                            Name = "Quidco",
                            UpdatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3164),
                            Website = "https://www.quidco.com"
                        },
                        new
                        {
                            Id = new Guid("33b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3171),
                            Description = "Smart app offering cashback used to pay down mortgages",
                            IsActive = true,
                            Name = "Sprive",
                            UpdatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3171),
                            Website = "https://sprive.com"
                        },
                        new
                        {
                            Id = new Guid("44b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3174),
                            Description = "Credit card reward schemes and retailer cashback partnerships",
                            IsActive = true,
                            Name = "Barclaycard",
                            UpdatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3174),
                            Website = "https://www.barclaycard.co.uk"
                        },
                        new
                        {
                            Id = new Guid("55b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3176),
                            Description = "1% cashback on eligible everyday debit card spending",
                            IsActive = true,
                            Name = "Chase",
                            UpdatedDate = new DateTime(2026, 7, 1, 8, 22, 15, 891, DateTimeKind.Utc).AddTicks(3176),
                            Website = "https://www.chase.co.uk"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Retailers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Offer", b =>
                {
                    b.HasOne("SaverSearch.Domain.Entities.OfferType", "OfferType")
                        .WithMany("Offers")
                        .HasForeignKey("OfferTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaverSearch.Domain.Entities.Provider", "Provider")
                        .WithMany("Offers")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaverSearch.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Offers")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferType");

                    b.Navigation("Provider");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.HasOne("SaverSearch.Domain.Entities.Category", "Category")
                        .WithMany("Retailers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Category", b =>
                {
                    b.Navigation("Retailers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.OfferType", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
