"""
rule_engine/defaults.py
=======================
Simplified 12-category system.  Merchants provide the detail; categories
provide the overview.
"""
from __future__ import annotations

DEFAULT_CATEGORIES: list[tuple[str, int]] = [
    ("Income",        10),
    ("Housing",       20),
    ("Food & Drink",  30),
    ("Transport",     40),
    ("Shopping",      50),
    ("Hobbies",       60),
    ("Travel",        70),
    ("Finance",       80),
    ("Health",        90),
    ("Family",        100),
    ("Entertainment", 110),
    ("Other",         999),
]

BUILTIN_RULES: list[tuple[str, str]] = [

    # ── Food & Drink ─────────────────────────────────────────────────────
    ("TESCO",                   "Food & Drink"),
    ("SAINSBURYS",              "Food & Drink"),
    ("SAINSBURY",               "Food & Drink"),
    ("ASDA",                    "Food & Drink"),
    ("ALDI",                    "Food & Drink"),
    ("LIDL",                    "Food & Drink"),
    ("MORRISONS",               "Food & Drink"),
    ("WAITROSE",                "Food & Drink"),
    ("MARKS AND SPENCER FOOD",  "Food & Drink"),
    ("M AND S FOOD",            "Food & Drink"),
    ("CO-OP FOOD",              "Food & Drink"),
    ("COOP",                    "Food & Drink"),
    ("ICELAND",                 "Food & Drink"),
    ("DELIVEROO",               "Food & Drink"),
    ("JUST EAT",                "Food & Drink"),
    ("DOMINO",                  "Food & Drink"),
    ("DOMINOS",                 "Food & Drink"),
    ("PIZZA HUT",               "Food & Drink"),
    ("MCDONALDS",               "Food & Drink"),
    ("MCDONALD",                "Food & Drink"),
    ("KFC",                     "Food & Drink"),
    ("SUBWAY",                  "Food & Drink"),
    ("FIVE GUYS",               "Food & Drink"),
    ("BURGER KING",             "Food & Drink"),
    ("NANDOS",                  "Food & Drink"),
    ("PAPA JOHN",               "Food & Drink"),
    ("HUNGRY HOUSE",            "Food & Drink"),
    ("UBER EATS",               "Food & Drink"),
    ("CAFFE NERO",              "Food & Drink"),
    ("STARBUCKS",               "Food & Drink"),
    ("COSTA",                   "Food & Drink"),
    ("CAF LOCAL",               "Food & Drink"),
    ("PRET",                    "Food & Drink"),
    ("GREGGS",                  "Food & Drink"),
    ("COFFEE",                  "Food & Drink"),
    ("CAFE",                    "Food & Drink"),
    ("RESTAURANT",              "Food & Drink"),
    ("ZIZZI",                   "Food & Drink"),
    ("WAGAMAMA",                "Food & Drink"),
    ("FRANKIE AND BENNY",       "Food & Drink"),
    ("PIZZA EXPRESS",           "Food & Drink"),
    ("TGI FRIDAY",              "Food & Drink"),
    ("HARVESTER",               "Food & Drink"),
    ("WETHERSPOON",             "Food & Drink"),
    ("WEATHERSPOON",            "Food & Drink"),
    ("STONEGATE",               "Food & Drink"),

    # ── Transport ────────────────────────────────────────────────────────
    ("STAGECOACH",              "Transport"),
    ("TRAINLINE",               "Transport"),
    ("LNER",                    "Transport"),
    ("LNE RAILWAY",             "Transport"),
    ("NATIONAL RAIL",           "Transport"),
    ("GREATER ANGLIA",          "Transport"),
    ("SOUTHERN RAIL",           "Transport"),
    ("ARRIVA",                  "Transport"),
    ("FIRST GROUP",             "Transport"),
    ("TRANSLINK",               "Transport"),
    ("TFL",                     "Transport"),
    ("TRANSPORT FOR LONDON",    "Transport"),
    ("CITY MAPPER",             "Transport"),
    ("EUROSTAR",                "Transport"),
    ("UBER",                    "Transport"),
    ("BOLT",                    "Transport"),
    ("BLACK TAXI",              "Transport"),
    ("BLACKTAXI",               "Transport"),
    ("ADDISON LEE",             "Transport"),
    ("SHELL",                   "Transport"),
    ("ESSO",                    "Transport"),
    ("TEXACO",                  "Transport"),
    ("GULF",                    "Transport"),
    ("TOTAL ENERGY",            "Transport"),
    ("MOTO",                    "Transport"),
    ("ROADCHEF",                "Transport"),
    ("BP",                      "Transport"),
    ("PARKING",                 "Transport"),
    ("NCP",                     "Transport"),
    ("RINGO",                   "Transport"),
    ("PAYBYPHONE",              "Transport"),
    ("HALFORDS",                "Transport"),
    ("KWIK FIT",                "Transport"),
    ("KWIKFIT",                 "Transport"),

    # ── Housing ──────────────────────────────────────────────────────────
    ("BRITISH GAS",             "Housing"),
    ("EDF",                     "Housing"),
    ("EON",                     "Housing"),
    ("OCTOPUS",                 "Housing"),
    ("BULB",                    "Housing"),
    ("SCOTTISH POWER",          "Housing"),
    ("THAMES WATER",            "Housing"),
    ("SEVERN TRENT",            "Housing"),
    ("ANGLIAN WATER",           "Housing"),
    ("SOUTHERN WATER",          "Housing"),
    ("BT GROUP",                "Housing"),
    ("SKY",                     "Housing"),
    ("VIRGIN MEDIA",            "Housing"),
    ("VM PERSONAL",             "Housing"),
    ("TALKTALK",                "Housing"),
    ("PLUSNET",                 "Housing"),
    ("VODAFONE",                "Housing"),
    ("O2",                      "Housing"),
    ("EE",                      "Housing"),
    ("THREE",                   "Housing"),
    ("GIFFGAFF",                "Housing"),
    ("SMARTY",                  "Housing"),
    ("LEBARA",                  "Housing"),
    ("INSURANCE",               "Housing"),
    ("AVIVA",                   "Housing"),
    ("AXA",                     "Housing"),
    ("LEGAL AND GENERAL",       "Housing"),
    ("DIRECT LINE",             "Housing"),
    ("ADMIRAL",                 "Housing"),
    ("COMPARE THE MARKET",      "Housing"),
    ("COUNCIL TAX",             "Housing"),
    ("COUNCIL",                 "Housing"),

    # ── Shopping ─────────────────────────────────────────────────────────
    ("AMAZON",                  "Shopping"),
    ("EBAY",                    "Shopping"),
    ("FIVERR",                  "Shopping"),
    ("ASOS",                    "Shopping"),
    ("ARGOS",                   "Shopping"),
    ("JOHN LEWIS",              "Shopping"),
    ("VERY",                    "Shopping"),
    ("DUNELM",                  "Shopping"),
    ("IKEA",                    "Shopping"),
    ("ETSY",                    "Shopping"),
    ("SHEIN",                   "Shopping"),
    ("TEMU",                    "Shopping"),
    ("PRIMARK",                 "Shopping"),
    ("H AND M",                 "Shopping"),
    ("ZARA",                    "Shopping"),
    ("MARKS AND SPENCER",       "Shopping"),
    ("M AND S",                 "Shopping"),
    ("RIVER ISLAND",            "Shopping"),
    ("TOPSHOP",                 "Shopping"),
    ("BOOHOO",                  "Shopping"),
    ("NEXT",                    "Shopping"),
    ("JD SPORTS",               "Shopping"),
    ("SPORTS DIRECT",           "Shopping"),
    ("NIKE",                    "Shopping"),
    ("ADIDAS",                  "Shopping"),
    ("FOOTLOCKER",              "Shopping"),
    ("NEW LOOK",                "Shopping"),
    ("DOROTHY PERKINS",         "Shopping"),
    ("BURTON",                  "Shopping"),
    ("CURRYS",                  "Shopping"),
    ("PC WORLD",                "Shopping"),
    ("APPLE STORE",             "Shopping"),
    ("B AND Q",                 "Shopping"),
    ("SCREWFIX",                "Shopping"),
    ("TOOLSTATION",             "Shopping"),
    ("WICKES",                  "Shopping"),
    ("HOMEBASE",                "Shopping"),
    ("TRAVIS PERKINS",          "Shopping"),

    # ── Hobbies ──────────────────────────────────────────────────────────
    ("GAMES WORKSHOP",          "Hobbies"),
    ("WARHAMMER",               "Hobbies"),
    ("HOBBYCRAFT",              "Hobbies"),
    ("MODELZONE",               "Hobbies"),
    ("NEON GOBLIN",             "Hobbies"),
    ("STEAM",                   "Hobbies"),
    ("PLAYSTATION",             "Hobbies"),
    ("XBOX",                    "Hobbies"),
    ("EPIC GAMES",              "Hobbies"),
    ("NINTENDO",                "Hobbies"),
    ("HUMBLE BUNDLE",           "Hobbies"),
    ("GOG.COM",                 "Hobbies"),
    ("WATERSTONES",             "Hobbies"),
    ("KINDLE",                  "Hobbies"),
    ("WHSmith",                 "Hobbies"),
    ("THE WORKS",               "Hobbies"),

    # ── Entertainment ────────────────────────────────────────────────────
    ("NETFLIX",                 "Entertainment"),
    ("SPOTIFY",                 "Entertainment"),
    ("GOOGLE PLAY",             "Entertainment"),
    ("APPLE.COM",               "Entertainment"),
    ("APPLE COM",               "Entertainment"),
    ("MICROSOFT",               "Entertainment"),
    ("LINKEDIN",                "Entertainment"),
    ("DISNEY",                  "Entertainment"),
    ("PRIME VIDEO",             "Entertainment"),
    ("NOW TV",                  "Entertainment"),
    ("NOWTV",                   "Entertainment"),
    ("AUDIBLE",                 "Entertainment"),
    ("YOUTUBE",                 "Entertainment"),
    ("ADOBE",                   "Entertainment"),
    ("DROPBOX",                 "Entertainment"),
    ("ICLOUD",                  "Entertainment"),
    ("GITHUB",                  "Entertainment"),
    ("UBER ONE",                "Entertainment"),
    ("AMAZON PRIME",            "Entertainment"),
    ("CINEMA",                  "Entertainment"),
    ("ODEON",                   "Entertainment"),
    ("VUE",                     "Entertainment"),
    ("CINEWORLD",               "Entertainment"),
    ("TICKETMASTER",            "Entertainment"),
    ("EVENTBRITE",              "Entertainment"),
    ("SEE TICKETS",             "Entertainment"),
    ("SKIDDLE",                 "Entertainment"),

    # ── Travel ───────────────────────────────────────────────────────────
    ("EASYJET",                 "Travel"),
    ("RYANAIR",                 "Travel"),
    ("JET2",                    "Travel"),
    ("TUI",                     "Travel"),
    ("BRITISH AIRWAYS",         "Travel"),
    ("BOOKING.COM",             "Travel"),
    ("BOOKING COM",             "Travel"),
    ("AIRBNB",                  "Travel"),
    ("EXPEDIA",                 "Travel"),
    ("HOTELS.COM",              "Travel"),
    ("LAST MINUTE",             "Travel"),
    ("ON THE BEACH",            "Travel"),
    ("LOVEHOLIDAYS",            "Travel"),
    ("HOLIDAY INN",             "Travel"),
    ("PREMIER INN",             "Travel"),
    ("TRAVELODGE",              "Travel"),
    ("MARRIOTT",                "Travel"),
    ("HILTON",                  "Travel"),
    ("IBIS",                    "Travel"),
    ("WIZZ AIR",                "Travel"),
    ("NORWEGIAN",               "Travel"),
    ("EUROCAR",                 "Travel"),
    ("HERTZ",                   "Travel"),
    ("ENTERPRISE CAR",          "Travel"),

    # ── Finance ──────────────────────────────────────────────────────────
    ("SPRIVE",                  "Finance"),
    ("MONEYBOX",                "Finance"),
    ("NUTMEG",                  "Finance"),
    ("VANGUARD",                "Finance"),
    ("CHIP",                    "Finance"),
    ("TRADING 212",             "Finance"),
    ("FREETRADE",               "Finance"),
    ("HARGREAVES",              "Finance"),
    ("AJ BELL",                 "Finance"),
    ("INTERACTIVE INVESTOR",    "Finance"),
    ("BANK CHARGE",             "Finance"),
    ("OVERDRAFT",               "Finance"),
    ("LATE PAYMENT",            "Finance"),
    ("ARRANGEMENT FEE",         "Finance"),
    ("BANK TRANSFER",           "Finance"),
    ("FASTER PAYMENT",          "Finance"),
    ("CASH WITHDRAWAL",         "Finance"),
    ("ATM",                     "Finance"),
    ("CASHPOINT",               "Finance"),

    # ── Health ───────────────────────────────────────────────────────────
    ("BOOTS",                   "Health"),
    ("SUPERDRUG",               "Health"),
    ("PHARMACY",                "Health"),
    ("LLOYDS PHARMACY",         "Health"),
    ("WELL PHARMACY",           "Health"),
    ("DENTIST",                 "Health"),
    ("DENTAL",                  "Health"),
    ("NHS",                     "Health"),
    ("OPTICIAN",                "Health"),
    ("OPTICAL",                 "Health"),
    ("AO OPTICAL",              "Health"),
    ("SPECSAVERS",              "Health"),
    ("BUPA",                    "Health"),
    ("PRIVATE HEALTH",          "Health"),
    ("PUREGYM",                 "Health"),
    ("PURE GYM",                "Health"),
    ("DAVID LLOYD",             "Health"),
    ("VIRGIN ACTIVE",           "Health"),
    ("FITNESS FIRST",           "Health"),
    ("THE GYM GROUP",           "Health"),
    ("GYM",                     "Health"),

    # ── Family ───────────────────────────────────────────────────────────
    ("PETS AT HOME",            "Family"),
    ("VET",                     "Family"),
    ("VETS",                    "Family"),
    ("PETPLAN",                 "Family"),
    ("UDEMY",                   "Family"),
    ("COURSERA",                "Family"),
    ("PLURALSIGHT",             "Family"),
    ("DUOLINGO",                "Family"),
    ("SCHOOL",                  "Family"),
    ("UNIVERSITY",              "Family"),
    ("COLLEGE",                 "Family"),
    ("SKILLSHARE",              "Family"),
    ("LINKEDIN LEARNING",       "Family"),
    ("NURSERY",                 "Family"),
    ("CHILDCARE",               "Family"),

    # ── Income ───────────────────────────────────────────────────────────
    ("AMAZON WEB SERVICE",      "Income"),
    ("HMRC",                    "Income"),
    ("UNIVERSAL CREDIT",        "Income"),
    ("DWP",                     "Income"),
    ("REFUND",                  "Income"),
    ("CASHBACK",                "Income"),

    # ── Other ────────────────────────────────────────────────────────────
    ("JUSTGIVING",              "Other"),
    ("CHARITY",                 "Other"),
    ("COMIC RELIEF",            "Other"),
    ("RED CROSS",               "Other"),
]


# ── Merchant Dictionary ────────────────────────────────────────────────────────
# Each entry: raw_keyword (matched against raw description), canonical_name,
# merchant_type, category.
# Multiple raw_keywords can resolve to the same canonical merchant.

MERCHANT_DICTIONARY: list[dict] = [
    # Employer / Income
    {"raw_keyword": "AMAZON WEB SERVICES",  "canonical_name": "Amazon Web Services",        "merchant_type": "Employer",            "category": "Income"},
    {"raw_keyword": "MRS N LOCK",           "canonical_name": "Mrs N Lock",                 "merchant_type": "Family Transfer",     "category": "Income"},
    {"raw_keyword": "JAMES N LOCK",         "canonical_name": "James N Lock",               "merchant_type": "Internal Transfer",   "category": "Income"},
    # Bank / Finance
    {"raw_keyword": "LLOYDS BANK",          "canonical_name": "Lloyds Bank",                "merchant_type": "Bank",                "category": "Finance"},
    {"raw_keyword": "VM PERSONAL LOANS",    "canonical_name": "Virgin Money Personal Loans", "merchant_type": "Loan",               "category": "Finance"},
    {"raw_keyword": "SPRIVE",               "canonical_name": "Sprive",                     "merchant_type": "Investment Platform", "category": "Finance"},
    {"raw_keyword": "TRADING212",           "canonical_name": "Trading212",                 "merchant_type": "Investment Platform", "category": "Finance"},
    {"raw_keyword": "TRADING 212",          "canonical_name": "Trading212",                 "merchant_type": "Investment Platform", "category": "Finance"},
    {"raw_keyword": "CHECKMYFILE",          "canonical_name": "CheckMyFile",                "merchant_type": "Financial Services",  "category": "Finance"},
    {"raw_keyword": "TV LICENSING",         "canonical_name": "TV Licensing",               "merchant_type": "Government",          "category": "Housing"},
    # Healthcare
    {"raw_keyword": "DONNA HARTNETT",       "canonical_name": "Donna Hartnett",             "merchant_type": "Healthcare",          "category": "Health"},
    {"raw_keyword": "RTW SURGERIES",        "canonical_name": "RTW Surgeries",              "merchant_type": "Healthcare",          "category": "Health"},
    {"raw_keyword": "OAKDALE VET",          "canonical_name": "Oakdale Vet Centre",         "merchant_type": "Healthcare",          "category": "Family"},
    # Standing Orders
    {"raw_keyword": "JENNA LYNNS",          "canonical_name": "Jenna Lynns",                "merchant_type": "Standing Order",      "category": "Family"},
    {"raw_keyword": "SPARRING PARTNERS",    "canonical_name": "Sparring Partners",          "merchant_type": "Utility",             "category": "Other"},
    # Food & Drink
    {"raw_keyword": "TESCO STORES",         "canonical_name": "Tesco",                      "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "TESCO EXTRA",          "canonical_name": "Tesco",                      "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "TESCO EXPRESS",        "canonical_name": "Tesco",                      "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "SAINSBURYS",           "canonical_name": "Sainsburys",                 "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "SAINSBURY",            "canonical_name": "Sainsburys",                 "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "LIDL",                 "canonical_name": "Lidl",                       "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "GREGGS",               "canonical_name": "Greggs",                     "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "CAFE LOCAL",           "canonical_name": "Cafe Local",                 "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "PRET A MANGER",        "canonical_name": "Pret A Manger",              "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "CAFFE NERO",           "canonical_name": "Caffe Nero",                 "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "STARBUCKS",            "canonical_name": "Starbucks",                  "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "DELIVEROO",            "canonical_name": "Deliveroo",                  "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "DOMINOS",              "canonical_name": "Domino's",                   "merchant_type": "Merchant",            "category": "Food & Drink"},
    {"raw_keyword": "DOMINO",              "canonical_name": "Domino's",                    "merchant_type": "Merchant",            "category": "Food & Drink"},
    # Transport
    {"raw_keyword": "UBER",                 "canonical_name": "Uber",                       "merchant_type": "Transport",           "category": "Transport"},
    {"raw_keyword": "STAGECOACH",           "canonical_name": "Stagecoach",                 "merchant_type": "Transport",           "category": "Transport"},
    {"raw_keyword": "LNER",                 "canonical_name": "LNER",                       "merchant_type": "Transport",           "category": "Transport"},
    {"raw_keyword": "TFL",                  "canonical_name": "TFL",                        "merchant_type": "Transport",           "category": "Transport"},
    {"raw_keyword": "BLACK TAXI",           "canonical_name": "Black Taxi",                 "merchant_type": "Transport",           "category": "Transport"},
    # Hobbies
    {"raw_keyword": "WARHAMMER",            "canonical_name": "Warhammer",                  "merchant_type": "Merchant",            "category": "Hobbies"},
    {"raw_keyword": "GAMES WORKSHOP",       "canonical_name": "Warhammer",                  "merchant_type": "Merchant",            "category": "Hobbies"},
    {"raw_keyword": "STEAM",                "canonical_name": "Steam",                      "merchant_type": "Merchant",            "category": "Hobbies"},
    # Shopping
    {"raw_keyword": "RICHARDSONS CYCLES",   "canonical_name": "Richardsons Cycles",         "merchant_type": "Merchant",            "category": "Shopping"},
    {"raw_keyword": "SUPER RIGS",           "canonical_name": "Super Rigs",                 "merchant_type": "Merchant",            "category": "Shopping"},
    # Family
    {"raw_keyword": "THE ENTERTAINER",      "canonical_name": "The Entertainer",            "merchant_type": "Merchant",            "category": "Family"},
]
