// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaverSearch.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SaverSearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaverSearchDbContext))]
    partial class SaverSearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SaverSearch.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23a2a3ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "TVs, laptops, phones, and smart home appliances",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("8b72de70-c081-420a-9d62-f6cb3ce183a3"),
                            Description = "Groceries, weekly shops, and household essentials",
                            IsActive = true,
                            Name = "Supermarkets"
                        },
                        new
                        {
                            Id = new Guid("501bd346-63e8-466d-b873-67ca2b6eb2b5"),
                            Description = "Clothing, footwear, and accessories",
                            IsActive = true,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = new Guid("3d64c148-d3c5-4148-912f-db4fe72b0c95"),
                            Description = "Furniture, garden, and home improvement decor",
                            IsActive = true,
                            Name = "Home"
                        },
                        new
                        {
                            Id = new Guid("9a8cd34a-9ef8-4ca7-9e7f-b67f2e1a3bc8"),
                            Description = "Hotels, flights, holidays, and transport",
                            IsActive = true,
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.ImportJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OffersAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffersDeactivated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffersDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffersUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffersValidated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationWarningCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName");

                    b.HasIndex("StartedAt");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsExclusive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("MaximumReward")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumSpend")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terms")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferTypeId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("ProviderId", "ExternalId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.OfferType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OfferTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Return of a percentage of the amount spent to the consumer",
                            Name = "Cashback"
                        },
                        new
                        {
                            Id = new Guid("22c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Direct price reduction applied to purchase price",
                            Name = "Discount"
                        },
                        new
                        {
                            Id = new Guid("33c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Loyalty system points earned per dollar/pound spent",
                            Name = "Reward Points"
                        },
                        new
                        {
                            Id = new Guid("44c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "A discount code or certificate for specific promotions",
                            Name = "Voucher"
                        },
                        new
                        {
                            Id = new Guid("55c223ad-cc52-472e-8390-50d41f3d3281"),
                            Description = "Cashback specifically directed to pay down linked mortgage balances",
                            Name = "Mortgage Cashback"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(5967),
                            Description = "UK's highest paying cashback site",
                            IsActive = true,
                            Name = "TopCashback",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(5968),
                            Website = "https://www.topcashback.co.uk"
                        },
                        new
                        {
                            Id = new Guid("22b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6720),
                            Description = "Great rates and easy cashback search",
                            IsActive = true,
                            Name = "Quidco",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6720),
                            Website = "https://www.quidco.com"
                        },
                        new
                        {
                            Id = new Guid("33b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6724),
                            Description = "Smart app offering cashback used to pay down mortgages",
                            IsActive = true,
                            Name = "Sprive",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6724),
                            Website = "https://sprive.com"
                        },
                        new
                        {
                            Id = new Guid("44b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6726),
                            Description = "Credit card reward schemes and retailer cashback partnerships",
                            IsActive = true,
                            Name = "Barclaycard",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6726),
                            Website = "https://www.barclaycard.co.uk"
                        },
                        new
                        {
                            Id = new Guid("55b223ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6728),
                            Description = "1% cashback on eligible everyday debit card spending",
                            IsActive = true,
                            Name = "Chase",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 698, DateTimeKind.Utc).AddTicks(6728),
                            Website = "https://www.chase.co.uk"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Retailers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0f2b3ad-cc52-472e-8390-50d41f3d3281"),
                            CategoryId = new Guid("23a2a3ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(969),
                            IsActive = true,
                            Name = "Amazon",
                            Slug = "amazon",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(970),
                            Website = "https://amazon.co.uk"
                        },
                        new
                        {
                            Id = new Guid("c0f2b3ad-cc52-472e-8390-50d41f3d3281"),
                            CategoryId = new Guid("23a2a3ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(1771),
                            IsActive = true,
                            Name = "Currys",
                            Slug = "currys",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(1771),
                            Website = "https://currys.co.uk"
                        },
                        new
                        {
                            Id = new Guid("b0f2b3ad-cc52-472e-8390-50d41f3d3281"),
                            CategoryId = new Guid("23a2a3ad-cc52-472e-8390-50d41f3d3281"),
                            CreatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(1776),
                            IsActive = true,
                            Name = "Argos",
                            Slug = "argos",
                            UpdatedDate = new DateTime(2026, 7, 1, 10, 51, 56, 701, DateTimeKind.Utc).AddTicks(1776),
                            Website = "https://argos.co.uk"
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.RetailerAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AliasName");

                    b.HasIndex("RetailerId");

                    b.ToTable("RetailerAliases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43fc3186-c08e-47d6-85ec-6bb8e0787f0e"),
                            AliasName = "Amazon",
                            RetailerId = new Guid("a0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("5fd83782-862a-450d-9082-6b5fc5b6724b"),
                            AliasName = "amazon.co.uk",
                            RetailerId = new Guid("a0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("e607d710-cb94-4045-a2df-251b989bc5fe"),
                            AliasName = "Amazon UK",
                            RetailerId = new Guid("a0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("daf7c97c-0ff8-44ec-bde1-2b8259598a39"),
                            AliasName = "Currys",
                            RetailerId = new Guid("c0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("5ecde822-ece3-45da-a40d-8543b108e041"),
                            AliasName = "Currys PC World",
                            RetailerId = new Guid("c0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("3b758414-69c0-44fc-ada6-0a997867210e"),
                            AliasName = "PC World",
                            RetailerId = new Guid("c0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("4f94ba77-a63a-45cc-af75-5167db778bd6"),
                            AliasName = "currys.co.uk",
                            RetailerId = new Guid("c0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("9dbbb772-5a20-4b0e-8d98-65306e8ec8fa"),
                            AliasName = "Argos",
                            RetailerId = new Guid("b0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        },
                        new
                        {
                            Id = new Guid("b8f5feba-0699-4dde-8cdb-5cde5af0add4"),
                            AliasName = "argos.co.uk",
                            RetailerId = new Guid("b0f2b3ad-cc52-472e-8390-50d41f3d3281")
                        });
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Offer", b =>
                {
                    b.HasOne("SaverSearch.Domain.Entities.OfferType", "OfferType")
                        .WithMany("Offers")
                        .HasForeignKey("OfferTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaverSearch.Domain.Entities.Provider", "Provider")
                        .WithMany("Offers")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaverSearch.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Offers")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferType");

                    b.Navigation("Provider");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.HasOne("SaverSearch.Domain.Entities.Category", "Category")
                        .WithMany("Retailers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.RetailerAlias", b =>
                {
                    b.HasOne("SaverSearch.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Aliases")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Category", b =>
                {
                    b.Navigation("Retailers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.OfferType", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SaverSearch.Domain.Entities.Retailer", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
